### ISSUE TITLE
is_rev_in_remote timesout on large repos

### ISSUE THREAD

**Issue by ryaminal** [ruifm/gitlinker.nvim#34]
**Is your feature request related to a problem? Please describe.**
`require'gitlinker'.get_buf_range_url('n')` timesout after 5 seconds

**Describe the solution you'd like**
A quick-ish short term solution would be to have an option to easily change the timeouts. This isn't the "desired" solution but it seems like it's the most likely "solution" to the problem.

**Describe alternatives you've considered**
Alternative solutions would be to either have an option or something that removes the need to make this call. Or, if the call is necessary if there is a way to cache the response. I wish my git skills/knowledge was greater but it isn't so I don't really know what this information is being used for.

**Additional context**
Currently, I am working in a fairly large monorepo.
A `git branch --remotes | wc -l` shows roughly 2525 remote branches.
I'm assuming that if I clean up remote branches, that this will be a non-problem, but I don't know how realistic that is to do.
So, the problem is that the default plenary job timeout appears to be 5s. The command from `is_rev_in_remote`(`git branch --remotes --contains HEAD`) takes almost 30 seconds to complete in the monorepo mentioned above. The culprit is the `--contains HEAD` portion of the command. I mean, the real problem is this gigantic monorepo with so many "dangling" branches.

**Comment by ruifm** [comment]
Sorry for the delay, I think https://github.com/ruifm/gitlinker.nvim/pull/37 should address the performance impact of repos with a lot of blobs since now the remote tracking branch is checked first.

You should only have this issue if no remote tracking branch is set for the current branch, which forces a search in the configured remote, commit by commit.

Let me know if the issue persists.
