### ISSUE TITLE
Support copying via OSC

### ISSUE THREAD

**Issue by j-hui** [ruifm/gitlinker.nvim#47]
**Is your feature request related to a problem? Please describe.**
Yanking to the system clipboard only works if the Neovim instance is running on your host machine; it doesn't work if it's running inside an SSH session, for example.

**Describe the solution you'd like**
Most popular terminal emulator seem to support the ANSI OSC52 sequence, an escape sequence that tells the terminal emulator to copy some text to the system clipboard.

Something like this is already implemented using [ojroques/vim-oscyank](https://github.com/ojroques/vim-oscyank).

It would be great if there were a gitlinker action that could do the same.

**Describe alternatives you've considered**

Perhaps this suggestion is simply out of the scope of this plugin (in which case this issue needn't be kept open except for reference).

In any case, the following `action_callback` makes use of vim-oscyank, and may be of interest to others:

```lua
require'gitlinker'.setup{                               
  opts = {                                              
    action_callback = function(url)                     
      vim.api.nvim_command('let @" = \'' .. url .. '\'')
      vim.fn.OSCYankString(url)                         
    end,                                                
  },                                                    
}                                                       
```

I also add the `url` to vim's unnamed register because I'm used to it being in sync with the system clipboard, but that's entirely optional.

**Comment by ruifm** [comment]
I did not know about OSC but sounds very interesting and useful for my ssh remote sessions.

Supporting OSC out-of-the-box is really out of scope for this plugin unless they include it in neovim core. Because of that, its support relies on an external plugin which makes that `action_callback` (although useful) not suited to be the default.

However, I would accept a PR that either:

* Adds an extra callback function with a different name that people can use
* Documents this usecase in the `README` + `help`
* Start a wiki with user contributed callbacks for the urls (maybe this is far fetched, I don't think there is a lot that can be done with git urls that is still useful but I maybe wrong).

**Comment by j-hui** [comment]
Totally understand about it being out of scope; just having `action_callback` gives users everything they need to make OSC yank work (like I did). The configuration isn't even that complicated.

I'll make a PR sometime soon.

**Comment by ruifm** [comment]
Closed by https://github.com/ruifm/gitlinker.nvim/pull/49
